---
- id: snykio:maven:com.parasoft:environment-manager:548698
  title: Credential Exposure
  description: |
    [com.parasoft:environment-manager][1] is a third party integration tool
    for Parasoft Environment Manager.

    Affected versions of this package are vulnerable to Credential Exposure.
    Jenkins Parasoft Environment Manager Plugin stores a password
    unencrypted in job `config.xml` files on the Jenkins master where it can
    be viewed by users with Extended Read permission, or access to the
    master file system.



    [1]: https://plugins.jenkins.io/environment-manager/
  affected_package: com.parasoft:environment-manager
  vulnerable_versions:
  - ">= 0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2020-2132
  cwe:
  - CWE-256
  disclosed_date: 2020-02-12
  created_date: 2020-02-13
  last_modified_date: 2020-02-13
  credit:
  - IB Boost
  - James Holderness
  references:
  - https://jenkins.io/security/advisory/2020-02-12/
  - https://plugins.jenkins.io/environment-manager
  source_url: https://snyk.io/vuln/SNYK-JAVA-COMPARASOFT-548698
