---
- id: ossindex:maven:org.jsecurity:jsecurity:343081
  title: '[CVE-2010-3863]  Improper Limitation of a Pathname to a Restricted Directory
    ("Path Traversal")'
  description: Apache Shiro before 1.1.0, and JSecurity 0.9.x, does not canonicalize
    URI paths before comparing them to entries in the shiro.ini file, which allows
    remote attackers to bypass intended access restrictions via a crafted request,
    as demonstrated by the /./account/index.jsp URI.
  affected_package: org.jsecurity:jsecurity
  vulnerable_versions:
  - 0.9.0
  package_manager: maven
  cve:
  - CVE-2010-3863
  disclosed_date: 2010-11-05
  created_date: 2010-11-05
  last_modified_date: 2017-04-19
  credit:
  - OSSIndex
  references:
  - http://archives.neohapsis.com/archives/fulldisclosure/2010-11/0020.html
  - http://osvdb.org/69067
  - http://secunia.com/advisories/41989
  - http://www.securityfocus.com/archive/1/archive/1/514616/100/0/threaded
  - http://www.securityfocus.com/bid/44616
  - http://www.vupen.com/english/advisories/2010/2888
  - http://xforce.iss.net/xforce/xfdb/62959
  source_url: https://ossindex.net/resource/package/7015268644/vulnerabilities
- id: snykio:maven:org.jsecurity:jsecurity:31217
  title: Directory Traversal
  description: |
    [`org.jsecurity:jsecurity`][1] Apache Shiro before 1.1.0, and JSecurity
    0.9.x, does not canonicalize URI paths before comparing them to entries
    in the shiro.ini file, which allows remote attackers to bypass intended
    access restrictions via a crafted request, as demonstrated by the
    /./account/index.jsp URI.



    [1]: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jsecurity%22
    \nA Directory Traversal attack (also known as path traversal) aims to
    access files and directories that are stored outside the intended
    folder. By manipulating files with \"dot-dot-slash (../)\" sequences and
    its variations, or by using absolute file paths, it may be possible to
    access arbitrary files and directories stored on file system, including
    application source code, configuration, and other critical system files.

    Directory Traversal vulnerabilities can be generally divided into two
    types:

    * **Information Disclosure**\: Allows the attacker to gain information
      about the folder structure or read the contents of sensitive files on
      the system.

    `st` is a module for serving static files on web pages, and contains a
    [vulnerability of this type][1]. In our example, we will serve files
    from the `public` route.

    If an attacker requests the following URL from our server, it will in
    turn leak the sensitive private key of the root user.

        curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.ssh/id_rsa

    **Note** `%2e` is the URL encoded version of `.` (dot).

    * **Writing arbitrary files**\: Allows the attacker to create or replace
      existing files. This type of vulnerability is also known as
      `Zip-Slip`.

    One way to achieve this is by using a malicious `zip` archive that holds
    path traversal filenames. When each filename in the zip archive gets
    concatenated to the target extraction folder, without validation, the
    final path ends up outside of the target folder. If an executable or a
    configuration file is overwritten with a file containing malicious code,
    the problem can turn into an arbitrary code execution issue quite
    easily.

    The following is an example of a `zip` archive with one benign file and
    one malicious file. Extracting the malicious file will result in
    traversing out of the target folder, ending up in `/root/.ssh/`
    overwriting the `authorized_keys` file:

        2018-04-15 22:04:29 .....           19           19  good.txt
        2018-04-15 22:04:42 .....           20           20  ../../../../../../root/.ssh/authorized_keys



    [1]: https://snyk.io/vuln/npm:st:20140206
  affected_package: org.jsecurity:jsecurity
  vulnerable_versions:
  - ">= 0.9.0"
  severity: medium
  package_manager: maven
  cve:
  - CVE-2010-3863
  cwe:
  - CWE-22
  disclosed_date: 2010-11-05
  created_date: 2014-01-10
  last_modified_date: 2014-01-10
  credit:
  - Unknown
  references:
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2010-3863
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGJSECURITY-31217
