---
- id: snykio:go:github.com/docker/libcontainer:469152
  title: Access Restriction Bypass
  description: |
    [github.com/docker/libcontainer][1] is a package that provides a native
    Go implementation for creating containers with namespaces, cgroups,
    capabilities, and filesystem access controls.

    Affected versions of this package are vulnerable to Access Restriction
    Bypass. AppArmor restriction bypass is possible because
    `libcontainer/rootfs_linux.go` incorrectly checks mount targets, and
    thus a malicious Docker image can mount over a `/proc` directory.



    [1]: https://github.com/docker/libcontainer
  affected_package: github.com/docker/libcontainer
  vulnerable_versions:
  - "<1.0.0-rc9"
  severity: medium
  package_manager: go
  cve:
  - CVE-2019-16884
  cwe:
  - CWE-284
  disclosed_date: 2019-09-22
  created_date: 2019-09-26
  last_modified_date: 2019-09-26
  credit:
  - Unknown
  references:
  - https://github.com/crosbymichael/runc/commit/78dce1cf1ec36bbe7fe6767bdb81f7cbf6d34d70
  - https://github.com/opencontainers/runc/issues/2128
  - https://github.com/opencontainers/runc/pull/2129
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDOCKERLIBCONTAINER-469152
- id: snykio:go:github.com/docker/libcontainer:50012
  title: Symlink Attack
  description: |
    Affected version of [`github.com/docker/libcontainer`][1] are vulnerable
    to Symlink Attacks. Libcontainer and Docker Engine before 1.6.1 opens
    the file-descriptor passed to the pid-1 process before performing the
    chroot, which allows local users to gain privileges via a symlink attack
    in an image.



    [1]: https://github.com/docker/libcontainer
  affected_package: github.com/docker/libcontainer
  vulnerable_versions:
  - "<1.6.1"
  severity: high
  package_manager: go
  cve:
  - CVE-2015-3627
  cwe:
  - CWE-59
  disclosed_date: 2015-08-06
  created_date: 2015-08-06
  last_modified_date: 2015-08-06
  credit:
  - Tõnis Tiigi
  references:
  - http://packetstormsecurity.com/files/131835/Docker-Privilege-Escalation-Information-Disclosure.html
  - http://seclists.org/fulldisclosure/2015/May/28
  - https://github.com/docker/libcontainer/commit/46132cebcf391b56842f5cf9b247d508c59bc625
  - https://groups.google.com/forum/#%21searchin/docker-user/1.6.1/docker-user/47GZrihtr-4/nwgeOOFLexIJ
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-3627
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDOCKERLIBCONTAINER-50012
