---
- id: snykio:pypi:products.ldapuserfolder:40628
  title: Access Restriction Bypass
  description: |
    [`products.ldapuserfolder`][1] is a LDAP-enabled Zope 2 user folder.

    Affected versions of this package vulnerable to Access Restriction
    Bypass attacks. The authenticate function in
    LDAPUserFolder/LDAPUserFolder.py in zope-ldapuserfolder 2.9-1 does not
    verify the password for the emergency account, which allows remote
    attackers to gain privileges.



    [1]: https://pypi.python.org/pypi/Products.LDAPUserFolder
  affected_package: products.ldapuserfolder
  vulnerable_versions:
  - "< 2.20"
  severity: high
  package_manager: pypi
  cve:
  - CVE-2010-2944
  cwe:
  - CWE-287
  disclosed_date: 2010-08-20
  created_date: 2017-10-25
  last_modified_date: 2017-10-25
  credit:
  - Unknown
  references:
  - https://nvd.nist.gov/vuln/detail/CVE-2010-2944
  source_url: https://snyk.io/vuln/SNYK-PYTHON-PRODUCTSLDAPUSERFOLDER-40628
